name: Lint YML
on:
  push:
    paths:
      - '**.yml'
    pull_request:
      types: [ opened, edited, synchronize, reopened, ready_for_review ]
      paths:
        - '**.yml'
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true
jobs:
  lint-yml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Lint yaml files
        uses: ibiqlik/action-yamllint@v3
